version: "3.8"

services:
  sim2sim:
    image: sim2sim:v0.0.1
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    stdin_open: true
    tty: true
    environment:
      NVIDIA_DRIVER_CAPABILITIES: compute,utility,graphics
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.cache/:/home/user/.cache/
      - $PWD:/workspace
    working_dir: /workspace
    command: /bin/bash
    ports:
      - "7007:7007"
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
