from sim2sim.mesh_processing.identity_mesh_processor import IdentityMeshProcessor
from sim2sim.mesh_processing.quadric_decimation_mesh_processor import QuadricDecimationMeshProcessor
from sim2sim.mesh_processing.sphere_mesh_processor import SphereMeshProcessor
from sim2sim.mesh_processing.convex_decomp_mesh_processor import ConvexDecompMeshProcessor
from sim2sim.mesh_processing.col_aware_decomp_mesh_processor import CoACDMeshProcessor
from sim2sim.mesh_processing.metaball_mesh_processor import MetaBallMeshProcessor
